name: severnaya_korzina_admin
description: Админ панель для управления Северной корзиной
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # Управление состоянием
  provider: ^6.1.1
  
  # Хранение данных
  shared_preferences: ^2.2.2
  
  # UI компоненты
  data_table_2: ^2.5.9
  fl_chart: ^0.65.0
  
  # Утилиты
  intl: ^0.19.0
  uuid: ^4.2.1
  http: ^1.4.0
  file_picker: ^10.2.0
  image_picker: ^1.0.4
  image: ^4.1.3
  permission_handler: ^10.4.5  # Более стабильная версия
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true